# https://doc.rust-lang.org/stable/clippy/index.html

doc-valid-idents = ["WebAssembly", "MongoDB", "JetStream", "NATS", "OpenTelemetry"]

allowed-duplicate-crates = [
  "addr2line",
  "base64",
  "bitflags",
  "core-foundation",
  "dashmap",
  "embedded-io",
  "getrandom",
  "hashbrown",
  "gimli",
  "hashbrown",
  "indexmap",
  "linux-raw-sys",
  "object",
  "prost",
  "prost-derive",
  "rand",
  "rand_chacha",
  "rand_core",
  "rustix",
  "rustls",
  "rustls-native-certs",
  "rustls-webpki",
  "schemars",
  "security-framework",
  "socket2",
  "thiserror",
  "thiserror-impl",
  "tokio-rustls",
  "wasi",
  "webpki-roots",
  "windows-link",
  "windows-result",
  "windows-strings",
  "windows-sys",
  "windows-targets",
  "windows_aarch64_gnullvm",
  "windows_aarch64_msvc",
  "windows_i686_gnu",
  "windows_i686_gnullvm",
  "windows_i686_msvc",
  "windows_x86_64_gnu",
  "windows_x86_64_gnullvm",
  "windows_x86_64_msvc",
]
