name: sql

services:
  sql:
    extends:
      file: ../docker/resources.yaml
      service: wasm32
    build:
      args:
        FEATURES: http,otel,sql,postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      - postgres
      - otelcol

  postgres:
    extends:
      file: ../docker/resources.yaml
      service: postgres

include:
  - ../docker/opentelemetry.yaml
