
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[[exemptions.addr2line]]
version = "0.25.1"
criteria = "safe-to-deploy"

[[exemptions.ahash]]
version = "0.8.12"
criteria = "safe-to-deploy"

[[exemptions.async-compression]]
version = "0.4.32"
criteria = "safe-to-deploy"

[[exemptions.async-lock]]
version = "3.4.1"
criteria = "safe-to-deploy"

[[exemptions.async-nats]]
version = "0.44.2"
criteria = "safe-to-deploy"

[[exemptions.axum]]
version = "0.8.6"
criteria = "safe-to-deploy"

[[exemptions.axum-core]]
version = "0.5.5"
criteria = "safe-to-deploy"

[[exemptions.axum-macros]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.azure_core]]
version = "0.29.1"
criteria = "safe-to-deploy"

[[exemptions.azure_core_macros]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.azure_identity]]
version = "0.29.0"
criteria = "safe-to-deploy"

[[exemptions.azure_security_keyvault_secrets]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.base64ct]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.bincode]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.bincode_derive]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "2.10.0"
criteria = "safe-to-deploy"

[[exemptions.bitvec]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.bson]]
version = "2.15.0"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.2.43"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.42"
criteria = "safe-to-deploy"

[[exemptions.compression-codecs]]
version = "0.4.31"
criteria = "safe-to-deploy"

[[exemptions.compression-core]]
version = "0.4.29"
criteria = "safe-to-deploy"

[[exemptions.concurrent-queue]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.const-hex]]
version = "1.17.0"
criteria = "safe-to-deploy"

[[exemptions.const-oid]]
version = "0.9.6"
criteria = "safe-to-deploy"

[[exemptions.const-random]]
version = "0.1.18"
criteria = "safe-to-deploy"

[[exemptions.const-random-macro]]
version = "0.1.16"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.21"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek]]
version = "4.1.3"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek-derive]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.darling]]
version = "0.21.3"
criteria = "safe-to-deploy"

[[exemptions.darling_core]]
version = "0.21.3"
criteria = "safe-to-deploy"

[[exemptions.darling_macro]]
version = "0.21.3"
criteria = "safe-to-deploy"

[[exemptions.data-encoding]]
version = "2.9.0"
criteria = "safe-to-deploy"

[[exemptions.der]]
version = "0.7.10"
criteria = "safe-to-deploy"

[[exemptions.deranged]]
version = "0.5.5"
criteria = "safe-to-deploy"

[[exemptions.derive-syn-parse]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.derive-where]]
version = "1.6.0"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-deploy"

[[exemptions.ed25519]]
version = "2.2.3"
criteria = "safe-to-deploy"

[[exemptions.ed25519-dalek]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.enum-as-inner]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.event-listener]]
version = "5.4.1"
criteria = "safe-to-deploy"

[[exemptions.event-listener-strategy]]
version = "0.5.4"
criteria = "safe-to-deploy"

[[exemptions.fallible-iterator]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.funty]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.9"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.hickory-proto]]
version = "0.24.4"
criteria = "safe-to-deploy"

[[exemptions.hickory-resolver]]
version = "0.24.4"
criteria = "safe-to-deploy"

[[exemptions.hyper-rustls]]
version = "0.27.7"
criteria = "safe-to-deploy"

[[exemptions.hyper-timeout]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.ipconfig]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.ipnet]]
version = "2.11.0"
criteria = "safe-to-deploy"

[[exemptions.iri-string]]
version = "0.7.8"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.82"
criteria = "safe-to-deploy"

[[exemptions.lru-cache]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.lru-slab]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.macro_magic]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.macro_magic_core]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.macro_magic_core_macros]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.macro_magic_macros]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.matchit]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.maybe-owned]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.md-5]]
version = "0.10.6"
criteria = "safe-to-deploy"

[[exemptions.mongocrypt]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.mongocrypt-sys]]
version = "0.1.4+1.12.0"
criteria = "safe-to-deploy"

[[exemptions.mongodb]]
version = "3.3.0"
criteria = "safe-to-deploy"

[[exemptions.mongodb-internal-macros]]
version = "3.3.0"
criteria = "safe-to-deploy"

[[exemptions.nkeys]]
version = "0.4.5"
criteria = "safe-to-deploy"

[[exemptions.nu-ansi-term]]
version = "0.50.3"
criteria = "safe-to-deploy"

[[exemptions.nuid]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.37.3"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.21.3"
criteria = "safe-to-deploy"

[[exemptions.openssl]]
version = "0.10.74"
criteria = "safe-to-deploy"

[[exemptions.openssl-sys]]
version = "0.9.110"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry-http]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry-otlp]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry-proto]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry_sdk]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.parking]]
version = "2.2.1"
criteria = "safe-to-deploy"

[[exemptions.pbkdf2]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.pem-rfc7468]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.pin-project]]
version = "1.1.10"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.1.10"
criteria = "safe-to-deploy"

[[exemptions.pkcs8]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.pkg-config]]
version = "0.3.32"
criteria = "safe-to-deploy"

[[exemptions.portable-atomic]]
version = "1.11.1"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.21"
criteria = "safe-to-deploy"

[[exemptions.proptest]]
version = "1.9.0"
criteria = "safe-to-deploy"

[[exemptions.prost]]
version = "0.14.1"
criteria = "safe-to-deploy"

[[exemptions.prost-derive]]
version = "0.14.1"
criteria = "safe-to-deploy"

[[exemptions.quinn]]
version = "0.11.9"
criteria = "safe-to-deploy"

[[exemptions.quinn-proto]]
version = "0.11.13"
criteria = "safe-to-deploy"

[[exemptions.quinn-udp]]
version = "0.5.14"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.41"
criteria = "safe-to-deploy"

[[exemptions.r-efi]]
version = "5.3.0"
criteria = "safe-to-deploy"

[[exemptions.radium]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.rand_xorshift]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.5.18"
criteria = "safe-to-deploy"

[[exemptions.resolv-conf]]
version = "0.7.5"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.17.14"
criteria = "safe-to-deploy"

[[exemptions.rustc_version_runtime]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.rustls]]
version = "0.22.4"
criteria = "safe-to-deploy"

[[exemptions.rustls]]
version = "0.23.34"
criteria = "safe-to-deploy"

[[exemptions.rustls-native-certs]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.rustls-pemfile]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.rustls-pki-types]]
version = "1.13.0"
criteria = "safe-to-deploy"

[[exemptions.rustls-webpki]]
version = "0.102.8"
criteria = "safe-to-deploy"

[[exemptions.rustls-webpki]]
version = "0.103.7"
criteria = "safe-to-deploy"

[[exemptions.schannel]]
version = "0.1.28"
criteria = "safe-to-deploy"

[[exemptions.schemars]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.schemars]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.security-framework]]
version = "2.11.1"
criteria = "safe-to-deploy"

[[exemptions.security-framework-sys]]
version = "2.15.0"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.228"
criteria = "safe-to-deploy"

[[exemptions.serde_core]]
version = "1.0.228"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.228"
criteria = "safe-to-deploy"

[[exemptions.serde_nanos]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.serde_urlencoded]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.serde_with]]
version = "3.15.1"
criteria = "safe-to-deploy"

[[exemptions.serde_with_macros]]
version = "3.15.1"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-registry]]
version = "1.4.6"
criteria = "safe-to-deploy"

[[exemptions.signatory]]
version = "0.27.1"
criteria = "safe-to-deploy"

[[exemptions.spki]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.stable_deref_trait]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.stringprep]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.sync_wrapper]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.system-configuration]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.system-configuration-sys]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.23.0"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.3.44"
criteria = "safe-to-deploy"

[[exemptions.time-core]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.time-macros]]
version = "0.2.24"
criteria = "safe-to-deploy"

[[exemptions.tiny-keccak]]
version = "2.0.2"
criteria = "safe-to-deploy"

[[exemptions.tinyvec]]
version = "1.10.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-rustls]]
version = "0.25.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-rustls]]
version = "0.26.4"
criteria = "safe-to-deploy"

[[exemptions.tokio-websockets]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.tonic]]
version = "0.14.2"
criteria = "safe-to-deploy"

[[exemptions.tonic-prost]]
version = "0.14.2"
criteria = "safe-to-deploy"

[[exemptions.tower-layer]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.tracing-opentelemetry]]
version = "0.32.0"
criteria = "safe-to-deploy"

[[exemptions.tryhard]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.typed-builder]]
version = "0.20.1"
criteria = "safe-to-deploy"

[[exemptions.typed-builder-macro]]
version = "0.20.1"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.19.0"
criteria = "safe-to-deploy"

[[exemptions.typespec]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.typespec_client_core]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.typespec_macros]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.unarray]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.untrusted]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.unty]]
version = "0.0.4"
criteria = "safe-to-deploy"

[[exemptions.uuid]]
version = "1.18.1"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.virtue]]
version = "0.0.18"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.105"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-futures]]
version = "0.4.55"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.105"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.105"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.105"
criteria = "safe-to-deploy"

[[exemptions.wasm-streams]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.82"
criteria = "safe-to-deploy"

[[exemptions.web-time]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.webpki-roots]]
version = "0.26.11"
criteria = "safe-to-deploy"

[[exemptions.webpki-roots]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.widestring]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.winreg]]
version = "0.50.0"
criteria = "safe-to-deploy"

[[exemptions.wyz]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.8.27"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.8.27"
criteria = "safe-to-deploy"

[[exemptions.zeroize]]
version = "1.8.2"
criteria = "safe-to-deploy"
