name: http-redis-cache

secrets:
  credibil:
    environment: CARGO_REGISTRIES_CREDIBIL_TOKEN

services:
  proxy:
    image: http-redis-cache:latest
    container_name: http-redis-cache
    env_file: ../../.env
    build:
      context: ../..
      dockerfile: Dockerfile
      secrets:
        - credibil
      args:
        BIN: standard
    volumes:
       - ../../target/wasm32-wasip2/release/examples/http_redis_cache.wasm:/app.wasm
    ports:
      - 8080:8080
    depends_on:
      - redis
      - otelcol

  otelcol:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 4317:4317
      - 4318:4318
    depends_on:
      - jaeger
      - prometheus
      
  jaeger:
    image: jaegertracing/jaeger:latest
    ports:
      - 16686:16686

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090 
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-remote-write-receiver
      # - --log.level=debug

  redis:
    image: redis:latest
    command: redis-server --save "" --appendonly no
    ports:
      - 6379:6379
