name: messaging

services:
  messaging:
    extends:
      file: ../../docker/service.yaml
      service: wasm32
    build:
      args:
        FEATURES: http,otel,messaging,kafka
    depends_on:
      - kafka
      - otelcol

include:
  - oci://ghcr.io/credibil/compose-kafka:latest
  - oci://ghcr.io/credibil/compose-opentelemetry:latest
