name: messaging

services:
  messaging:
    extends:
      file: ../../docker/service.yaml
      service: wasm32
    build:
      args:
        FEATURES: http,otel,messaging,kafka
    depends_on:
      - topics
      - otelcol

  topics:
    image: apache/kafka:latest
    command: |
      sh -c '
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists --topic a;
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists --topic b;
      '
    depends_on:
      kafka:
        condition: service_healthy

  kafka:
    extends:
      file: oci://ghcr.io/credibil/compose-resources:latest
      service: kafka

include:
  - oci://ghcr.io/credibil/compose-opentelemetry:latest
