name: messaging

services:
  messaging:
    extends:
      file: ../../docker/service.yaml
      service: wasm32
    build:
      args:
        FEATURES: http,otel,messaging,kafka
    depends_on:
      - topics
      - otelcol

  topics:
    extends:
      file: oci://ghcr.io/credibil/compose-resources:latest
      service: kafka-topics

  kafka:
    extends:
      file: oci://ghcr.io/credibil/compose-resources:latest
      service: kafka

include:
  - oci://ghcr.io/credibil/compose-opentelemetry:latest
