name: keyvalue

services:
  keyvalue:
    extends:
      file: ../docker/resources.yaml
      service: wasm32
    build:
      args:
        FEATURES: http,otel,keyvalue,nats
    depends_on:
      - nats
      - otelcol

  nats:
    extends:
      file: ../docker/resources.yaml
      service: nats

include:
  - ../docker/opentelemetry.yaml