name: keyvalue

services:
  keyvalue:
    extends:
      file: ../../docker/service.yaml
      service: wasm32
    build:
      args:
        FEATURES: http,otel,keyvalue,redis
    depends_on:
      - redis
      - otelcol

  redis:
    extends:
      file: oci://ghcr.io/credibil/compose-resources:latest
      service: redis

include:
  - oci://ghcr.io/credibil/compose-opentelemetry:latest
