name: blobstore

services:
  blobstore:
    extends:
      file: ../docker/resources.yaml
      service: wasm32
    build:
      args:
        FEATURES: http,otel,blobstore,redis
    depends_on:
      - redis
      - otelcol

  redis:
    extends:
      file: ../docker/resources.yaml
      service: redis

include:
  - ../docker/opentelemetry.yaml
