name: otel

services:
  http:
    extends:
      file: ../../docker/service.yaml
      service: wasm32
    build:
      args:
        FEATURES: http-server
    depends_on:
      - otelcol

include:
  - oci://ghcr.io/credibil/compose-otelcol:latest
